language: node_js

node_js:
  - "node"

branches:
  only:
    - master

script:
  - npm run build

before_install:
  - git config --global user.email "sneethling@mozilla.com"
  - git config --global user.name "schalkneethling"

deploy:
  local_dir: docs
  name: schalkneethling
  email: sneethling@mozilla.com
  provider: pages
  skip_cleanup: true
  github_token: GITHUB_TOKEN
  on:
    branch: master
