language: node_js

node_js:
  - "node"

branches:
  only:
    - master

script:
  - npm run build

deploy:
  local_dir: docs
  provider: pages
  skip_cleanup: true
  github_token: GITHUB_TOKEN
  on:
    branch: master
